apiVersion: v1
kind: Service
metadata:
  name: tasky-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: tasky
  ports:
    - port: 80
      targetPort: 8080