apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      serviceAccountName: tasky-admin-sa  
      containers:
      - name: tasky
        image: 495599779952.dkr.ecr.us-east-1.amazonaws.com/tasky:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb://admin:supersecret123@10.0.1.23:27017/?authSource=admin"
        - name: SECRET_KEY
          value: "supersecret123"
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-lb
spec:
  type: LoadBalancer
  selector:
    app: tasky
  ports:
    - port: 80
      targetPort: 8080
